spring.application.name=prenotazione

# Configurazione MySQL

spring.datasource.url=jdbc:mysql://localhost:3306/prenotazione
spring.datasource.username=root
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazioni JPA/Hibernate

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8081

external.service.url=http://localhost:8080/jwt/has-access
get.userId.from.jwt=http://localhost:8080/jwt/get-userid-from-jwt-token/
get.saved.codicePrenotazione.in.user=http://localhost:8080/utente/users/save-prenotazione
