# Configurazione generale per l'ambiente non Docker (default)
spring.application.name=prenotazione

# Configurazione MySQL
spring.datasource.url=jdbc:mysql://mysql:3306/prenotazione
spring.datasource.username=root
spring.datasource.password=rootroot
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configurazione JPA/Hibernate
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

# Configurazioni per i servizi esterni
external.service.url=${EXTERNAL_SERVICE_URL:http://localhost:8080/jwt/has-access}
get.userId.from.jwt=${GET_USER_ID_URL:http://localhost:8080/jwt/get-username-from-jwt-token/}
get.saved.codicePrenotazione.in.user=${SAVE_COD_PRONTO_URL:http://localhost:8080/utente/users/save-prenotazione}

# Profilo Docker attivato solo in ambiente Docker
spring.config.activate.on-profile=docker
